### ISSUE TITLE
Enable ESLint

### ISSUE THREAD

**Issue by 0xflotus** [0xflotus/ip2d#669]
The goal of this issue is to enable ESLint to lint the Typescript Code for this project.

**Comment by harish08102004** [comment]
hey @0xflotus I can work on this.

**Comment by 0xflotus** [comment]
Feel free :-)

**Comment by harish08102004** [comment]
hey @0xflotus I have raised the PR. Please review it and merge it. 
btw, can you add level label for this issue.
