### ISSUE TITLE
More tests for IPv6

### ISSUE THREAD

**Issue by 0xflotus** [0xflotus/ip2d#679]
The goal for this issue is to write more tests for the **toIPv6()** and **fromIPv6()** functions.

e.g.:

ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff -> 340282366920938463463374607431768211455
ffff:ffff::ffff:ffff:ffff:ffff          -> 340282366841710300967557013911933812735
ffff:ffff::                             -> 340282366841710300949110269838224261120

**Comment by vidhvath28** [comment]
@0xflotus   I've worked on enhancing the test coverage for the IPv4 and IPv6 conversion utilities. The new test cases cover boundary values, arithmetic operations, error handling, and various edge cases, ensuring the reliability and correctness of these utilities.

I would appreciate it if you could review and accept this PR #680 . Thank you!
