### ISSUE TITLE
Enable linting stage in pipeline

### ISSUE THREAD

**Issue by 0xflotus** [0xflotus/ip2d#693]
The goal of this issue is to integrate the linting stage via `npm lint` into the current [workflow pipeline](https://github.com/0xflotus/ip2d/actions).

**Comment by NawinKumarSharma** [comment]
@0xflotus  can i work on this?

**Comment by 0xflotus** [comment]
> @0xflotus can i work on this?

Of Course :-)

**Comment by NawinKumarSharma** [comment]
@0xflotus , can you review this #695
