### ISSUE TITLE
Run the tests on several Node versions in the pipeline

### ISSUE THREAD

**Issue by 0xflotus** [0xflotus/ip2d#696]
The goal of this issue is to run the tests on several currently supported NodeJS versions in the pipeline.

**Comment by Emilio-PdeA** [comment]
Hello @0xflotus, I would like to work on this task but I have a question:
- In what other Node.js versions would you like to be tested with?

**Comment by 0xflotus** [comment]
> Hello @0xflotus, I would like to work on this task but I have a question:
> 
>     * In what other Node.js versions would you like to be tested with?

Let's say 18 (LTS), 20 (LTS) and 22 (Current)
