### ISSUE TITLE
[DOCS] Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Emilio-PdeA** [0xflotus/ip2d#697]
Since people can contribute to this repository, I think it would be helpful to have a `CONTRIBUTING.md` file as a guide for contributions in this repository.

What do you think?

**Comment by 0xflotus** [comment]
Feel free to add one :-)

**Comment by Pariharx7** [comment]
Hey, I'd like to contribute on the issue.

**Comment by 0xflotus** [comment]
@Pariharx7 Are you still working on this?

**Comment by Pariharx7** [comment]
Yep

**Comment by Pariharx7** [comment]
can you describe the specific rules you want to have in the CONTRIBUTING.md or should i write the ones that are provided by GitHub itself

**Comment by 0xflotus** [comment]
I don't have specific rules for this repository.
